name: CI

on: push

jobs:
  super-lint-Unittest:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my code
        uses: actions/checkout@v3

      - name: Run Super-Lint
        uses: github/super-linter@v5
        env:
            VALIDATE_ALL_CODEBASE: false
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Unit-testing
        run: python test.py

    
